// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfMTp-HBZnjnNNvpPVsmxVpJtIHFU2T00',
    appId: '1:255034545471:web:e14bc4403c872c81766f8a',
    messagingSenderId: '255034545471',
    projectId: 'flutter-places-2398',
    authDomain: 'flutter-places-2398.firebaseapp.com',
    storageBucket: 'flutter-places-2398.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX9Pv1yp6L6QqCLt-n1Ex-t34BPfsJOdY',
    appId: '1:255034545471:android:db31ac50d5f7cfca766f8a',
    messagingSenderId: '255034545471',
    projectId: 'flutter-places-2398',
    storageBucket: 'flutter-places-2398.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrwDTyUfG-hOKjinc0Vr42M2qtd9CLWBg',
    appId: '1:255034545471:ios:f26fa72110c72edc766f8a',
    messagingSenderId: '255034545471',
    projectId: 'flutter-places-2398',
    storageBucket: 'flutter-places-2398.firebasestorage.app',
    iosBundleId: 'com.example.flutterNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrwDTyUfG-hOKjinc0Vr42M2qtd9CLWBg',
    appId: '1:255034545471:ios:f26fa72110c72edc766f8a',
    messagingSenderId: '255034545471',
    projectId: 'flutter-places-2398',
    storageBucket: 'flutter-places-2398.firebasestorage.app',
    iosBundleId: 'com.example.flutterNews',
  );
}
